# Generated by Django 3.0.4 on 2020-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('condition', models.CharField(choices=[('G', 'Good'), ('N', 'Normal'), ('B', 'Bad')], max_length=1)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150)),
            ],
        ),
    ]
