# Generated by Django 3.0.4 on 2020-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('P', 'Phones'), ('EA', 'Electronics & Appliances'), ('F', 'Fashion'), ('B', 'Books'), ('C', 'Cars'), ('BK', 'Bikes'), ('FR', 'Furniture'), ('OT', 'Other')], max_length=2),
        ),
    ]
