# Generated by Django 3.0.4 on 2020-03-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
    ]
